# Generated by Django 5.1.4 on 2024-12-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Geolocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geo_x", models.FloatField(default=0)),
                ("geo_y", models.FloatField(default=0)),
                ("geo_lon", models.FloatField(default=0)),
                ("geo_lat", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Neighbourhood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "neighbourhood_id",
                    models.CharField(default="No location", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offense_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offense_category_id", models.CharField(max_length=100)),
                ("offense_category_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Offense_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offense_type_id", models.CharField(max_length=100)),
                ("offense_type_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_address", models.CharField(max_length=256)),
                ("district_id", models.IntegerField(default=0)),
                ("precinct_id", models.IntegerField(default=0)),
                (
                    "geo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="incidents.geolocation",
                    ),
                ),
                (
                    "neighbourhood_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="incidents.neighbourhood",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_occurrence_date", models.DateTimeField()),
                ("reported_date", models.DateTimeField()),
                ("is_crime", models.BooleanField()),
                ("is_traffic", models.BooleanField()),
                ("victim_count", models.IntegerField(default=0)),
                (
                    "offense_category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="incidents.offense_category",
                    ),
                ),
                (
                    "offense_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="incidents.offense_type",
                    ),
                ),
            ],
        ),
    ]
